apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - port: 80
    targetPort: vproapp-port
    protocol: TCP
    nodePort: 30763
  selector:
    app: vproapp
  type: LoadBalancer
