apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprodb
  labels:
    app: vprodb
spec:
  selector:
    matchLabels:
      app: vprodb
  replicas: 3
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: isrealurephu/vprofiledb:V1
        ports:
        - name: vprodb-port
          containerPort: 3306
        env: 
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: db-pass
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: vprodb-vol
      volumes:
      - name: vprodb-vol
        persistentVolumeClaim:
         claimName: vprodb-pv-claim


#        env:
#         - name: MYSQL_ROOT_PASSWORD
#           value: "vprodbpass"


---

apiVersion: v1

kind: PersistentVolume

metadata:

  name: vprodb-pv

  labels:

    app: vprodb

spec:

  storageClassName: manual

  capacity:

    storage: 10Gi

  accessModes:

    - ReadWriteOnce

  hostPath:

    path: "/mnt/data"

---

apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: vprodb-pv-claim

spec:

  storageClassName: manual

  accessModes:

    - ReadWriteOnce

  resources:

    requests:

      storage: 3Gi

